// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQB8YFkzjy5oyzEuYdm-2FIJUDgVRhmGA',
    appId: '1:614140672196:web:71cda07b68984d880b7191',
    messagingSenderId: '614140672196',
    projectId: 'indian-chilli-db',
    authDomain: 'indian-chilli-db.firebaseapp.com',
    databaseURL: 'https://indian-chilli-db-default-rtdb.firebaseio.com',
    storageBucket: 'indian-chilli-db.firebasestorage.app',
    measurementId: 'G-Z6WH99KH88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEi1a1YFZq-RdLDRcnjQ10q6MGYg4yjhI',
    appId: '1:614140672196:android:0f0d97d13a5afeab0b7191',
    messagingSenderId: '614140672196',
    projectId: 'indian-chilli-db',
    databaseURL: 'https://indian-chilli-db-default-rtdb.firebaseio.com',
    storageBucket: 'indian-chilli-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbjd69Ii5QGe4F4RFLemaao65Repx8Dxg',
    appId: '1:614140672196:ios:fd2b5f829f371fb90b7191',
    messagingSenderId: '614140672196',
    projectId: 'indian-chilli-db',
    databaseURL: 'https://indian-chilli-db-default-rtdb.firebaseio.com',
    storageBucket: 'indian-chilli-db.firebasestorage.app',
    iosBundleId: 'com.example.indianChilliRestaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbjd69Ii5QGe4F4RFLemaao65Repx8Dxg',
    appId: '1:614140672196:ios:fd2b5f829f371fb90b7191',
    messagingSenderId: '614140672196',
    projectId: 'indian-chilli-db',
    databaseURL: 'https://indian-chilli-db-default-rtdb.firebaseio.com',
    storageBucket: 'indian-chilli-db.firebasestorage.app',
    iosBundleId: 'com.example.indianChilliRestaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQB8YFkzjy5oyzEuYdm-2FIJUDgVRhmGA',
    appId: '1:614140672196:web:a04bbc99e521d2210b7191',
    messagingSenderId: '614140672196',
    projectId: 'indian-chilli-db',
    authDomain: 'indian-chilli-db.firebaseapp.com',
    databaseURL: 'https://indian-chilli-db-default-rtdb.firebaseio.com',
    storageBucket: 'indian-chilli-db.firebasestorage.app',
    measurementId: 'G-Q6JLR7CE4H',
  );
}
